const express = require("express");
const cors = require("cors");
const connectDB = require("./Config/db");
const app = express();
const AdminRoutes = require("./routes/AdminRoutes");
const AuthRoutes = require("./routes/AuthRoutes");
const jobRoutes = require("./routes/JobRoutes");
const applicationRoutes = require("./routes/ApplicationRoutes");
const savedJobRoutes = require("./routes/SavedJobRoutes");
connectDB();
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/admin", AdminRoutes);
app.use("/api/auth", AuthRoutes);
app.use("/api/jobs", jobRoutes);
app.use("/api/applications", applicationRoutes);
app.use("/api/saved-jobs", savedJobRoutes);
app.use("/uploads", express.static("uploads"));
app.listen(5000, () => console.log("server is running  port 5000!!!"));
